export default function Head() {
  return (
    <>
      <title>
          MOVIZOO
            </title>
      <meta 
        content="width=device-width, initial-scale=1" name="viewport" />
      <meta 
        name="description" content="Generated by create next app" />
      <link 
        rel="icon" 
          href="https://movizoo.id/wp-content/uploads/2022/11/cropped-Movizoo_600x600-1-120x40.png" 
            className=""/>
    </>
  )
}
