export default function privacypolicy() {
    return (
        <>
            <div className="mx-auto text-justify">
                <div
                    className="px-2 hover:bg-slate-100 block rounded-md shadow-md">
                    01
                    <div
                        className="px-4 text-lg font-semibold">
                        PRIVACY POLICY
                    </div>
                    <div
                        className="px-9 shadow-2xl rounded-lg text-justify">
                        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                        <br />
                        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
                        <br />
                        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                        For the purposes of this Privacy Policy:

                        <li className="py-2">
                            Account means a unique account created for You to access our Service or parts of our Service.
                        </li>
                        <br />
                        <li>
                            Affiliate means an entity that controls, is controlled by or is under common control with a party,
                            <br />
                            <p className="px-6">
                                where contact means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
                            </p>
                        </li>
                        <br />
                        <li>
                            Company (referred to as either the Company, We, Us or Our in this Agreement)
                            <br />
                            <p className="px-6">
                                refers to MoviZoo, Jl. R.Patah III No.3, RT.1RW/RW.3, Selong, Kec. Kby. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12110.
                            </p>
                        </li>
                        <br />
                        <li>
                            Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                        </li>
                        <br />
                        <li>
                            Country refers to: Indonesia
                        </li>
                        <br />
                        <li>
                            Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
                        </li>
                        <br />
                        <li>
                            Personal Data is any information that relates to an identified or identifiable individual.
                        </li>
                        <br />
                        <li>
                            Service refers to the Website.
                        </li>
                        <br />
                        <li>
                            Service Provider means any natural or legal person who processes the data on behalf of the Company.
                            <br />
                            <p className="px-6">It refers to third-party companies or individuals employed by the Company to facilitate the Service,
                                <br />
                                to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                        </li>
                        <br />
                        <li>
                            Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.
                        </li>
                        <br />
                        <li>
                            Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                        </li>
                        <br />
                        <li>
                            Website refers to movizoo, accessible from https://movizoo.id
                        </li>
                        <br />
                        <li>
                            You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                        </li>
                    </div>
                </div>
                <div
                    className="py-2 px-2 hover:bg-slate-100 block rounded-md shadow-md">
                    02
                    <div
                        className="px-4 text-lg font-semibold">
                        Collecting and Using Your Personal Data
                    </div>
                    <div
                        className="px-9 shadow-2xl rounded-lg text-justify">
                        Types of Data Collected Personal Data While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You.
                        <br /> Personally identifiable information may include, but is not limited to:
                        <li
                            className="py-2">
                            Email address
                        </li>
                        <br />
                        <li>
                            First name and last name
                        </li>
                        <br />
                        <li>
                            Phone number
                        </li>
                        <br />
                        <li>
                            Address, State, Province, ZIP/Postal code, City
                        </li>
                        <br />
                        <li>
                            Usage Data
                        </li>
                    </div>
                </div>
                <div
                    className="px-2  block rounded-md shadow-md">
                    03
                    <div
                        className="px-4 text-lg font-semibold">
                        Usage Data
                    </div>
                    <div
                        className="px-9 shadow-2xl rounded-lg text-justify">
                        Usage Data is collected automatically when using the Service.
                        <br />
                        Usage Data may include information such as Your Devices Internet Protocol address (e.g. IP address), browser type, browser version,
                        <br />
                        the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                        <br />
                        When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use,
                        <br />
                        Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                        <br />
                        We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                    </div>
                </div>
                <div
                    className="px-2 hover:bg-slate-100 block rounded-md shadow-md">
                    04
                    <div
                        className="px-4 text-lg font-semibold">
                        Information from Third-Party Social Media Services
                    </div>
                    <div
                        className="px-9 shadow-2xl rounded-lg text-justify">
                        The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:
                        <li
                            className="py-2">
                            Google

                        </li>
                        <br />
                        <li>
                            Facebook

                        </li>
                        <br />
                        <li>
                            Instagram

                        </li>
                        <br />
                        <li>
                            Twitter

                        </li>
                        <br />
                        <li>
                            LinkedIn

                        </li>
                        <br />
                        <p>
                            If You decide to register through or otherwise grant us access to a Third-Party Social Media Service,
                            <br />
                            We may collect Personal data that is already associated with Your Third-Party Social Media Services account, such as Your name, Your email address, Your activities or Your contact list associated with that account.
                            <br />
                            You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Services account. If You choose to provide such information and Personal Data,
                            <br />
                            during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.
                        </p>
                    </div>
                </div>
                <div
                    className="py-2 px-2 hover:bg-slate-100 block rounded-md shadow-md">
                    05
                    <div
                        className="px-4 text-lg font-semibold">
                        Tracking Technologies and Cookies
                    </div>
                    <div
                        className="px-9 shadow-2xl rounded-lg text-justify">
                        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information.
                        <br />
                        Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
                        <li
                            className="py-2">
                            Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                        </li>
                        <br />
                        <li>
                            Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
                        </li>
                        <br />
                        <p className="px-6">
                            Cookies can be Persistent or Session Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the Privacy Policies website article.
                            We use both Session and Persistent Cookies for the purposes set out below:</p>
                        <br />
                        <li>
                            Necessary / Essential Cookies
                            <br />
                            Type: Session Cookies
                            <br />
                            Administered by: Us
                            <br />
                            <p
                                className="px-4">
                                Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.
                                <br />
                                They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                            </p>
                        </li>
                        <br />
                        <li>
                            Cookies Policy / Notice Acceptance Cookies
                            <p>
                                Type: Persistent Cookies
                                Administered by: Us
                                Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
                            </p>
                        </li>
                        <br />
                        <li>
                            Functionality Cookies
                            <p>
                                Type: Persistent Cookies
                                Administered by: Us
                                Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
                            </p>
                        </li>
                        <p className="py-2">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
                    </div>
                </div>
            </div>
        </>
    )
}